sudo: required
language: bash
services:
  - docker

install:
  - docker build -t serve:latest .
  - docker run -d -p 8443:443 -v /srv:/app/files --name serve serve:latest

script:
  - docker ps | grep serve                                                            # container
  - echo "yolo" > /srv/test.txt
  - curl -k -X GET https://127.0.0.1:8443/test.txt | grep "HTTP/1.1 401"              # unauthorized
  - curl -k -X GET https://127.0.0.1:8443/test.txt --user user:password | grep yolo   # get file
