sudo: required
language: bash
services:
  - docker

install:
  - mkdir files
  - docker build -t serve:latest .
  - docker run -d -p 127.0.0.1:443:443 -v `pwd`/files:/app/files --name serve serve:latest
  - sleep 2 && docker logs serve

script:
  - docker ps | grep serve                                                                      # container
  - echo "yolo" > ./files/test.txt
  - sleep 2 && curl -kI -X GET https://127.0.0.1:443/test.txt | grep "HTTP/1.1 401"             # unauthorized
  - sleep 2 && curl -k -X GET https://127.0.0.1:443/test.txt --user user:password | grep yolo   # get file
